### PR TITLE
Fix for loading cohorts and strata from package

### LINKED ISSUE #43: Error while doing runStudy
After doing the cohort diagnostics, and then doing runStudy I got this error: 
Error: Can't subset columns that don't exist.
x Column `name` doesn't exist.

<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x Column `name` doesn't exist.
Backtrace:
     █
  1. └─PioneerWatchfulWaiting::runStudy(...)
  2.   └─PioneerWatchfulWaiting:::loadCohortsForExportFromPackage(cohortIds = counts$cohortId)
  3.     ├─base::rbind(cohorts, targetStrataXref[cols])
  4.     │ └─base::rbind(deparse.level, ...)
  5.     ├─targetStrataXref[cols]
  6.     ├─readr:::`[.spec_tbl_df`(targetStrataXref, cols)
  7.     ├─base::NextMethod(`[`)
  8.     └─tibble:::`[.tbl_df`(targetStrataXref, cols)
  9.       └─tibble:::vectbl_as_col_location(...)
 10.         ├─tibble:::subclass_col_index_errors(...)
 11.         │ └─base::withCallingHandlers(...)
 12.         └─vctrs::vec_as_location(j, n, names)
 13.           └─(function () ...
 14.             └─vctrs:::stop_subscript_oob(...)
 15.               └─vctrs:::stop_subscript(...)

### PR DESCRIPTION
**Pull request by MaximMoinat**
Column names differed between cohorts and strata due to previous fix.
Fixes #43

### CODE REVIEW

File: R/RunStudy.R [hunk 1]
```diff
@@ -518,20 +522,26 @@ loadCohortsFromPackage <- function(cohortIds) {
...
-  targetStrataXref$strataId <- NULL
+  targetStrataXref <- getTargetStrataXref() 
+  targetStrataXref <- targetStrataXref %>% 
+    dplyr::rename(cohortName = name) %>%
+    dplyr::mutate(cohortFullName = cohortName,
+                  targetId = NULL,
+                  strataId = NULL)
   
   cols <- names(cohorts)
   cohorts <- rbind(cohorts, targetStrataXref[cols])
```
Comment (MaximMoinat) [inline R/RunStudy.R:547]: dplyr row binding is more forgiving if columns don't match. Will just fill NA.
```suggestion
  cohorts <- dplyr::bind_rows(cohorts, targetStrataXref)
```
